name: The Art of MokMok
favicon: null
layout_spectrum: 0.09262306848540902
typography_spectrum: 0.9934093826450408
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000116'
    - '#ffffff'
    - '#009cb5'
    - '#82caf0'
    - '#ffc929'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
