name: The Art of MokMok
favicon: null
layout_spectrum: 0.51689
typography_spectrum: 0.52289
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#210035'
    - '#91184d'
    - '#fee353'
    - '#c1552e'
    - '#f0983f'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
